version: '3.8'

services:
  user_vault_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: user_vault:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=user_vault_db
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE=${DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - image_folder=./Uploads
    volumes:
      - ./Uploads:/app/Uploads
    depends_on:
      user_vault_db:
        condition: service_healthy
    networks:
      - app-network

  user_vault_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge